### ISSUE TITLE
PHP GitHub WorkFlow sets up Python environment

### ISSUE THREAD

**Issue by mcasperson** [OctopusSamples/content-team-apps#10]
The PHP builder includes this:

```
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
```

This is obviously not useful in a PHP build.
